/**
 * The type for the available default icons
 */
export type IIcons = {
    [P in
        | "search"
        | "arrowUp"
        | "arrowDown"
        | "arrowRight"
        | "arrowLeft"
        | "contextMenu"
        | "settings"
        | "window"
        | "select"
        | "move"
        | "moveVertical"
        | "moveHorizontal"
        | "show"
        | "hide"
        | "comment"
        | "download"
        | "upload"
        | "file"
        | "wifi"
        | "launch"
        | "exit"
        | "edit"
        | "delete"
        | "refresh"
        | "home"
        | "favorite"
        | "code"
        | "terminal"
        | "send"
        | "undo"
        | "redo"
        | "play"
        | "pause"
        | "folder"
        | "folderOpen"
        | "open"
        | "menu"
        | "session"
        | "return"
        | "help"
        | "applets"]: JSX.Element;
};
