import {IKeyId, keyIds} from "./keyIds";
import {IKeyName, keyNames} from "./keyNames";

/** All valid key matchers */
export const keys = {...keyIds, ...keyNames};

/** A valid key matcher */
export type IKeyMatcher = keyof typeof keys;

/** A mapping from key ids to the simplified names of those keys */
export const keyIdMapping: {[K in IKeyId]: IKeyName} = {
    altLeft: "alt",
    altRight: "alt",
    arrowDown: "down",
    arrowLeft: "left",
    arrowRight: "right",
    arrowUp: "up",
    backquote: "backquote",
    backslash: "backslash",
    backspace: "backspace",
    bracketLeft: "bracketLeft",
    bracketRight: "bracketRight",
    comma: "comma",
    controlLeft: "ctrl",
    controlRight: "ctrl",
    delete: "delete",
    digit0: "0",
    digit1: "1",
    digit2: "2",
    digit3: "3",
    digit4: "4",
    digit5: "5",
    digit6: "6",
    digit7: "7",
    digit8: "8",
    digit9: "9",
    end: "end",
    enter: "enter",
    equal: "equal",
    escape: "esc",
    f1: "f1",
    f2: "f2",
    f3: "f3",
    f4: "f4",
    f5: "f5",
    f6: "f6",
    f7: "f7",
    f8: "f8",
    f9: "f9",
    f10: "f10",
    f11: "f11",
    f12: "f12",
    f13: "f13",
    f14: "f14",
    f15: "f15",
    f16: "f16",
    f17: "f17",
    f18: "f18",
    f19: "f19",
    home: "home",
    insert: "insert",
    keyA: "a",
    keyB: "b",
    keyC: "c",
    keyD: "d",
    keyE: "e",
    keyF: "f",
    keyG: "g",
    keyH: "h",
    keyI: "i",
    keyJ: "j",
    keyK: "k",
    keyL: "l",
    keyM: "m",
    keyN: "n",
    keyO: "o",
    keyP: "p",
    keyQ: "q",
    keyR: "r",
    keyS: "s",
    keyT: "t",
    keyU: "u",
    keyV: "v",
    keyW: "w",
    keyX: "x",
    keyY: "y",
    keyZ: "z",
    metaLeft: "meta",
    metaRight: "meta",
    minus: "minus",
    pageDown: "pageDown",
    pageUp: "pageUp",
    period: "period",
    printscreen: "printscreen",
    quote: "quote",
    semicolon: "semicolon",
    shiftLeft: "shift",
    shiftRight: "shift",
    slash: "slash",
    space: "space",
    tab: "tab",
    contextMenu: "contextMenu",
};
